files: '.py'
repos:
-   repo: https://github.com/kynan/nbstripout
    rev: 0.6.0
    hooks:
    -   id: nbstripout
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        args: [-l 127]
-   repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
    -   id: flake8
        args: [--count, --select=E9, --select=F63, --select=F7, --select=F82, --show-source, --statistics]